/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.tipigao.motor3d;

import java.awt.event.MouseEvent;

/**
 *
 * @author Roberto
 */
public class Janela extends javax.swing.JFrame {

    MotorJogo jogo;
    
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        
        jogo = new Visor3D();
        jogo.setPainelDesenho(pnlDesenho);
        jogo.inicializa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDesenho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlDesenho.setBackground(new java.awt.Color(0, 0, 0));
        pnlDesenho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlDesenhoMouseDragged(evt);
            }
        });
        pnlDesenho.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                pnlDesenhoMouseWheelMoved(evt);
            }
        });
        pnlDesenho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDesenhoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pnlDesenhoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlDesenhoLayout = new javax.swing.GroupLayout(pnlDesenho);
        pnlDesenho.setLayout(pnlDesenhoLayout);
        pnlDesenhoLayout.setHorizontalGroup(
            pnlDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlDesenhoLayout.setVerticalGroup(
            pnlDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(pnlDesenho);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        jogo.atualizaValoresCena();
    }//GEN-LAST:event_formComponentResized

    private void pnlDesenhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDesenhoMousePressed
        jogo.mousePressionado(evt);
    }//GEN-LAST:event_pnlDesenhoMousePressed

    private void pnlDesenhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDesenhoMouseReleased
        jogo.mouseLiberado(evt);
    }//GEN-LAST:event_pnlDesenhoMouseReleased

    private void pnlDesenhoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pnlDesenhoMouseWheelMoved
        jogo.mouseRodaMovida(evt);
    }//GEN-LAST:event_pnlDesenhoMouseWheelMoved

    private void pnlDesenhoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDesenhoMouseDragged
        jogo.mouseMovido(evt);
    }//GEN-LAST:event_pnlDesenhoMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDesenho;
    // End of variables declaration//GEN-END:variables
}
